<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VNNOT01519" failures="4" tests="6" name="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" time="54.963" errors="1" timestamp="2025-06-22T14:02:57 GMT+07:00" skipped="0">
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="closeDriver" time="6.974">
    <error message="Cannot invoke &quot;org.monte.screenrecorder.ScreenRecorder$ScreenGrabber.close()&quot; because &quot;this.screenGrabber&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.monte.screenrecorder.ScreenRecorder$ScreenGrabber.close()" because "this.screenGrabber" is null
at org.monte.screenrecorder.ScreenRecorder.stop(ScreenRecorder.java:1232)
at com.anhtester.helpers.CaptureHelper.stopRecord(CaptureHelper.java:69)
at com.anhtester.common.BaseTest.closeDriver(BaseTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:805)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- closeDriver -->
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="loginSuccessFromDataProvider" time="13.180">
    <failure message="FAIL. Vẫn đang ở trang Login expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FAIL. Vẫn đang ở trang Login expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:439)
at com.anhtester.Bai30_Screenshot_Video_pages.LoginPage.verifyLoginSuccess(LoginPage.java:48)
at com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="loginSuccessFromDataProvider" time="9.742"/>
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="loginSuccessFromDataProvider" time="10.517">
    <failure message="FAIL. Vẫn đang ở trang Login expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FAIL. Vẫn đang ở trang Login expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:439)
at com.anhtester.Bai30_Screenshot_Video_pages.LoginPage.verifyLoginSuccess(LoginPage.java:48)
at com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="loginSuccessFromDataProvider" time="9.211">
    <failure message="FAIL. Vẫn đang ở trang Login expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FAIL. Vẫn đang ở trang Login expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:439)
at com.anhtester.Bai30_Screenshot_Video_pages.LoginPage.verifyLoginSuccess(LoginPage.java:48)
at com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest" name="loginSuccessFromDataProvider" time="5.339">
    <failure message="FAIL. Vẫn đang ở trang Login expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FAIL. Vẫn đang ở trang Login expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:439)
at com.anhtester.Bai30_Screenshot_Video_pages.LoginPage.verifyLoginSuccess(LoginPage.java:48)
at com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
</testsuite> <!-- com.anhtester.Bai30_Screenshot_Video_testcases.LoginTest -->
